# Generated by Django 2.1.1 on 2018-09-03 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('highlights', '0002_auto_20180903_0328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='thumbnail_url',
        ),
        migrations.AddField(
            model_name='book',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
