# Generated by Django 2.1.1 on 2018-09-05 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('highlights', '0003_auto_20180903_2025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='highlight',
            name='page_number',
        ),
    ]
