# Generated by Django 2.1.1 on 2019-01-23 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person_details', '0003_auto_20171119_2017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='link',
            name='link_type',
        ),
        migrations.AddField(
            model_name='link',
            name='svg',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='LinkType',
        ),
    ]
